#line 1 "seqc_lexer.c"

#line 3 "seqc_lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define seqc_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer seqc_create_buffer
#endif

#ifdef yy_delete_buffer
#define seqc_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer seqc_delete_buffer
#endif

#ifdef yy_scan_buffer
#define seqc_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer seqc_scan_buffer
#endif

#ifdef yy_scan_string
#define seqc_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string seqc_scan_string
#endif

#ifdef yy_scan_bytes
#define seqc_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes seqc_scan_bytes
#endif

#ifdef yy_init_buffer
#define seqc_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer seqc_init_buffer
#endif

#ifdef yy_flush_buffer
#define seqc_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer seqc_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define seqc_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state seqc_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define seqc_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer seqc_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define seqcpush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state seqcpush_buffer_state
#endif

#ifdef yypop_buffer_state
#define seqcpop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state seqcpop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define seqcensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack seqcensure_buffer_stack
#endif

#ifdef yylex
#define seqclex_ALREADY_DEFINED
#else
#define yylex seqclex
#endif

#ifdef yyrestart
#define seqcrestart_ALREADY_DEFINED
#else
#define yyrestart seqcrestart
#endif

#ifdef yylex_init
#define seqclex_init_ALREADY_DEFINED
#else
#define yylex_init seqclex_init
#endif

#ifdef yylex_init_extra
#define seqclex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra seqclex_init_extra
#endif

#ifdef yylex_destroy
#define seqclex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy seqclex_destroy
#endif

#ifdef yyget_debug
#define seqcget_debug_ALREADY_DEFINED
#else
#define yyget_debug seqcget_debug
#endif

#ifdef yyset_debug
#define seqcset_debug_ALREADY_DEFINED
#else
#define yyset_debug seqcset_debug
#endif

#ifdef yyget_extra
#define seqcget_extra_ALREADY_DEFINED
#else
#define yyget_extra seqcget_extra
#endif

#ifdef yyset_extra
#define seqcset_extra_ALREADY_DEFINED
#else
#define yyset_extra seqcset_extra
#endif

#ifdef yyget_in
#define seqcget_in_ALREADY_DEFINED
#else
#define yyget_in seqcget_in
#endif

#ifdef yyset_in
#define seqcset_in_ALREADY_DEFINED
#else
#define yyset_in seqcset_in
#endif

#ifdef yyget_out
#define seqcget_out_ALREADY_DEFINED
#else
#define yyget_out seqcget_out
#endif

#ifdef yyset_out
#define seqcset_out_ALREADY_DEFINED
#else
#define yyset_out seqcset_out
#endif

#ifdef yyget_leng
#define seqcget_leng_ALREADY_DEFINED
#else
#define yyget_leng seqcget_leng
#endif

#ifdef yyget_text
#define seqcget_text_ALREADY_DEFINED
#else
#define yyget_text seqcget_text
#endif

#ifdef yyget_lineno
#define seqcget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno seqcget_lineno
#endif

#ifdef yyset_lineno
#define seqcset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno seqcset_lineno
#endif

#ifdef yyget_column
#define seqcget_column_ALREADY_DEFINED
#else
#define yyget_column seqcget_column
#endif

#ifdef yyset_column
#define seqcset_column_ALREADY_DEFINED
#else
#define yyset_column seqcset_column
#endif

#ifdef yywrap
#define seqcwrap_ALREADY_DEFINED
#else
#define yywrap seqcwrap
#endif

#ifdef yyget_lval
#define seqcget_lval_ALREADY_DEFINED
#else
#define yyget_lval seqcget_lval
#endif

#ifdef yyset_lval
#define seqcset_lval_ALREADY_DEFINED
#else
#define yyset_lval seqcset_lval
#endif

#ifdef yyalloc
#define seqcalloc_ALREADY_DEFINED
#else
#define yyalloc seqcalloc
#endif

#ifdef yyrealloc
#define seqcrealloc_ALREADY_DEFINED
#else
#define yyrealloc seqcrealloc
#endif

#ifdef yyfree
#define seqcfree_ALREADY_DEFINED
#else
#define yyfree seqcfree
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define seqcwrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 80
#define YY_END_OF_BUFFER 81
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[168] =
    {   0,
        0,    0,   81,   79,   76,   77,   78,   64,   79,   70,
       63,   79,   58,   59,   68,   67,   55,   66,   62,   69,
       26,   26,   56,   52,   71,   57,   72,   75,   22,   22,
       60,   61,   73,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   53,   74,   54,   65,   76,   51,    0,
       31,    0,   38,   46,   39,    0,    0,    2,   36,   44,
       34,   45,   35,   28,    1,    3,   37,   29,   25,    0,
        0,    0,   26,   43,   48,   50,   49,   42,   22,    0,
        0,    0,    0,    0,   40,   22,   22,   22,   22,   22,
       14,   22,   22,   17,   22,   22,   22,   22,   22,   22,

       22,   41,   47,   30,    0,    0,   24,    0,   27,   23,
       33,   32,    0,    0,   22,   22,   22,   22,   22,   22,
       16,   22,   22,   22,   22,    7,   22,   22,   22,    0,
       28,    0,   29,    0,   22,   11,   22,   22,    5,   22,
       15,   22,   22,   22,   22,    8,    9,   22,   10,    4,
       22,   22,   22,   22,   22,   22,   21,   22,   22,   18,
       19,    6,   20,   22,   13,   12,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   27,   27,   29,   27,
       30,   30,   30,   30,   30,   31,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   32,   30,   30,
       33,   34,   35,   36,   30,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   30,   46,   47,   30,   48,
       49,   50,   30,   51,   52,   53,   54,   55,   56,   32,
       30,   30,   57,   58,   59,   60,    1,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,    1,    1,   62,   62,   62,   62,   62,   62,   62,

       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   64,
       64,   64,   64,   64,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[65] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    1,    1,    4,    4,    4,
        1,    1,    1,    1,    1,    1,    4,    4,    4,    5,
        5,    5,    1,    1,    1,    1,    4,    4,    4,    4,
        4,    4,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    1,    1,    1,    1,
        1,    5,    5,    5
    } ;

static const flex_int16_t yy_base[172] =
    {   0,
        0,    0,  253,  502,  250,  502,  502,  226,   59,  225,
       58,  212,  502,  502,   50,   55,  502,   54,   52,   63,
       70,   65,  502,  502,   53,  195,   67,  502,   33,   94,
      502,  502,  191,   50,   67,   74,   62,   56,   79,   86,
       91,   97,  108,  502,   49,  502,  502,  209,  502,  129,
      502,    0,  502,  502,  502,  130,  201,  502,  502,  502,
      502,  502,  502,  147,  502,  502,  502,  155,  161,  114,
      174,    0,  179,  177,  502,  502,  502,  162,  141,  124,
      117,  108,  134,  128,  502,  150,  154,  159,  163,  167,
      170,  176,  173,  179,  194,  197,  200,  203,  206,  216,

      210,  502,  502,  502,  268,  276,  164,  257,  279,    0,
      502,  502,   90,   67,  245,  249,  240,  254,  263,  260,
      257,  269,  274,  284,  277,  280,  294,  304,  288,  335,
      341,  344,  351,   56,  319,  310,  322,  331,  315,  326,
      334,  350,  340,  344,  360,  347,  353,  364,  356,  367,
      373,  378,  381,  384,  390,  394,  387,  401,  406,  398,
      409,  412,  415,  425,  418,  421,  502,  489,  494,  496,
      106
    } ;

static const flex_int16_t yy_def[172] =
    {   0,
      167,    1,  167,  167,  167,  167,  167,  167,  168,  167,
      167,  169,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  170,  170,
      167,  167,  167,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  167,  167,  167,  167,  167,  167,  168,
      167,  168,  167,  167,  167,  169,  169,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  171,  167,  167,  167,  167,  167,  167,  170,  167,
      167,  167,  168,  169,  167,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,

      170,  167,  167,  167,  167,  167,  167,  167,  167,  171,
      167,  167,  167,  167,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  167,
      167,  167,  167,  167,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,    0,  167,  167,  167,
      167
    } ;

static const flex_int16_t yy_nxt[567] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       23,   24,   25,   26,   27,   28,   29,   29,   29,   29,
       30,   29,   31,    4,   32,   33,   29,   34,   35,   36,
       37,   38,   29,   29,   39,   29,   29,   29,   29,   29,
       40,   41,   29,   29,   42,   43,   44,   45,   46,   47,
        4,    4,    4,    4,   51,   54,   58,   60,   62,   64,
       64,   64,  102,   59,   65,   74,   75,   63,   61,   66,
       68,   55,   73,   73,   73,   68,   67,   69,   69,   69,
       77,   78,   52,   71,   80,   81,   82,   70,   71,   83,

       86,   72,   84,   87,   93,   71,  103,   70,   92,  110,
       71,   80,   81,   82,   90,   88,   79,   80,   81,   82,
       94,   89,   91,   80,   81,   82,   95,  134,   80,   81,
       82,  107,  107,   98,   51,   80,   81,   82,  104,   51,
       80,   81,   82,   96,  100,   99,   97,   80,   81,   82,
       79,  101,   80,   81,   82,   80,   81,   82,   80,   81,
       82,   57,   52,   57,   64,   64,   64,   52,  114,   80,
       81,   82,   64,   64,   64,  105,   68,  113,   69,   69,
       69,  107,  107,  106,   79,  112,  108,  105,  108,   71,
      115,  109,  109,  109,   68,  106,   73,   73,   73,  118,

      111,   71,   80,   81,   82,  116,  117,   71,  119,   56,
       48,   80,   81,   82,   85,   80,   81,   82,   76,   71,
       80,   81,   82,  121,   80,   81,   82,  120,   80,   81,
       82,   80,   81,   82,   80,   81,   82,   80,   81,   82,
       80,   81,   82,  122,  125,   57,  123,  124,   53,   49,
      127,   48,  167,  126,  129,   80,   81,   82,   80,   81,
       82,   80,   81,   82,   80,   81,   82,   80,   81,   82,
      128,   80,   81,   82,  109,  109,  109,   80,   81,   82,
      130,  135,  130,  167,  167,  131,  131,  131,  132,  136,
      132,  137,  138,  133,  133,  133,  109,  109,  109,  140,

      141,   80,   81,   82,  139,  167,   80,   81,   82,  142,
       80,   81,   82,  167,  167,   80,   81,   82,   80,   81,
       82,   80,   81,   82,   80,   81,   82,  143,  144,  145,
       80,   81,   82,  146,  148,   80,   81,   82,   80,   81,
       82,   80,   81,   82,  147,   80,   81,   82,  167,   80,
       81,   82,  131,  131,  131,   80,   81,   82,  131,  131,
      131,  133,  133,  133,  149,   80,   81,   82,  133,  133,
      133,   80,   81,   82,  150,  151,   80,   81,   82,  152,
       80,   81,   82,   80,   81,   82,  153,   80,   81,   82,
      154,  155,   80,   81,   82,   80,   81,   82,  156,  167,

      167,   80,   81,   82,  157,   80,   81,   82,   80,   81,
       82,   80,   81,   82,   80,   81,   82,   80,   81,   82,
      158,   80,   81,   82,  159,   80,   81,   82,   80,   81,
       82,  161,  162,  160,   80,   81,   82,  163,  167,   80,
       81,   82,   80,   81,   82,   80,   81,   82,   80,   81,
       82,   80,   81,   82,  164,   80,   81,   82,  165,   80,
       81,   82,   80,   81,   82,  166,  167,   80,   81,   82,
       80,   81,   82,   80,   81,   82,   80,   81,   82,   80,
       81,   82,   80,   81,   82,  167,   80,   81,   82,   50,
      167,   50,   50,   50,   56,  167,  167,   56,   56,   79,

       79,    3,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167
    } ;

static const flex_int16_t yy_chk[567] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    9,   11,   15,   16,   18,   19,
       19,   19,   45,   15,   20,   25,   25,   18,   16,   20,
       22,   11,   22,   22,   22,   21,   20,   21,   21,   21,
       27,   27,    9,   22,   29,   29,   29,   21,   21,   30,

       34,   21,   30,   35,   38,   22,   45,   21,   37,  171,
       21,   34,   34,   34,   36,   35,  134,   38,   38,   38,
       39,   35,   36,   37,   37,   37,   40,  114,   35,   35,
       35,   70,   70,   42,   50,   36,   36,   36,   56,   83,
       39,   39,   39,   41,   43,   42,   41,   40,   40,   40,
      113,   43,   41,   41,   41,   30,   30,   30,   42,   42,
       42,   84,   50,   56,   64,   64,   64,   83,   82,   43,
       43,   43,   68,   68,   68,   64,   69,   81,   69,   69,
       69,  107,  107,   68,   80,   78,   71,   64,   71,   69,
       86,   71,   71,   71,   73,   68,   73,   73,   73,   89,

       74,   69,   79,   79,   79,   87,   88,   73,   90,   57,
       48,   86,   86,   86,   33,   87,   87,   87,   26,   73,
       88,   88,   88,   93,   89,   89,   89,   92,   90,   90,
       90,   91,   91,   91,   93,   93,   93,   92,   92,   92,
       94,   94,   94,   95,   97,   12,   95,   96,   10,    8,
       99,    5,    3,   98,  101,   95,   95,   95,   96,   96,
       96,   97,   97,   97,   98,   98,   98,   99,   99,   99,
      100,  101,  101,  101,  108,  108,  108,  100,  100,  100,
      105,  115,  105,    0,    0,  105,  105,  105,  106,  116,
      106,  117,  117,  106,  106,  106,  109,  109,  109,  119,

      120,  117,  117,  117,  118,    0,  115,  115,  115,  122,
      116,  116,  116,    0,    0,  118,  118,  118,  121,  121,
      121,  120,  120,  120,  119,  119,  119,  123,  124,  125,
      122,  122,  122,  127,  129,  123,  123,  123,  125,  125,
      125,  126,  126,  126,  128,  124,  124,  124,    0,  129,
      129,  129,  130,  130,  130,  127,  127,  127,  131,  131,
      131,  132,  132,  132,  135,  128,  128,  128,  133,  133,
      133,  136,  136,  136,  137,  138,  139,  139,  139,  140,
      135,  135,  135,  137,  137,  137,  142,  140,  140,  140,
      143,  144,  138,  138,  138,  141,  141,  141,  145,    0,

        0,  143,  143,  143,  148,  144,  144,  144,  146,  146,
      146,  142,  142,  142,  147,  147,  147,  149,  149,  149,
      151,  145,  145,  145,  152,  148,  148,  148,  150,  150,
      150,  154,  155,  153,  151,  151,  151,  156,    0,  152,
      152,  152,  153,  153,  153,  154,  154,  154,  157,  157,
      157,  155,  155,  155,  158,  156,  156,  156,  159,  160,
      160,  160,  158,  158,  158,  164,    0,  159,  159,  159,
      161,  161,  161,  162,  162,  162,  163,  163,  163,  165,
      165,  165,  166,  166,  166,    0,  164,  164,  164,  168,
        0,  168,  168,  168,  169,    0,    0,  169,  169,  170,

      170,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "seqc_lexer.l"
/* ============================================================================
 * Reconstructed from disassembly of _seqc_compiler.so
 * SeqC lexer — flex scanner for the SeqC language parser
 *
 * Original lexer: seqc_lex @0x2c7bb0 (6,902 bytes)
 * DFA: 177 states, 65 equivalence classes, 81 rules
 *
 * Flex DFA tables (binary addresses):
 *   yy_ec      @ 0x95fd40  uint8_t[256]   65 equivalence classes
 *   yy_accept  @ 0x95fe40  int16_t[177]   177 DFA states
 *   yy_chk     @ 0x95ffb0  int16_t[608]
 *   yy_base    @ 0x960470  int16_t[182]   177 states + 5 backing states
 *   yy_def     @ 0x9605e0  int16_t[182]
 *   yy_meta    @ 0x960750  uint8_t[65]    5 meta classes
 *   yy_nxt     @ 0x9607a0  int16_t[606]
 *
 * Action switch: jump table at 0x95fbf0, max action 82
 * ============================================================================ */
#line 21 "seqc_lexer.l"
#include "zhinst/seqc_parser_context.hpp"
#include "zhinst/expression.hpp"
#include "seqc_parser.tab.h"

/* bison-bridge expects YYSTYPE; with api.prefix {seqc}, bison generates SEQC_STYPE */
#define YYSTYPE SEQC_STYPE

#include <cstdio>
#include <cstring>
#include <cstdint>
#include <string>

/* Access the parser context via yyextra */
#define CTX  (static_cast<zhinst::SeqcParserContext*>(yyextra))
#line 857 "seqc_lexer.c"
#define YY_NO_INPUT 1
/* UTF-8 byte range definitions used in string literals */
#line 860 "seqc_lexer.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#define YY_EXTRA_TYPE zhinst::SeqcParserContext*

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

int yyget_debug ( yyscan_t yyscanner );

void yyset_debug ( int debug_flag , yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

FILE *yyget_in ( yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

FILE *yyget_out ( yyscan_t yyscanner );

void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

			int yyget_leng ( yyscan_t yyscanner );

char *yyget_text ( yyscan_t yyscanner );

int yyget_lineno ( yyscan_t yyscanner );

void yyset_lineno ( int _line_number , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

YYSTYPE * yyget_lval ( yyscan_t yyscanner );

void yyset_lval ( YYSTYPE * yylval_param , yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner);

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yylval = yylval_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
#line 51 "seqc_lexer.l"


#line 1133 "seqc_lexer.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 168 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 502 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 53 "seqc_lexer.l"
{
                /* Rule 1: Block comment start — action @0x2c8c47 */
                if (!CTX->isComment()) {
                    CTX->startBlockComment();
                }
            }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 60 "seqc_lexer.l"
{
                /* Rule 2: Block comment end — action @0x2c8d63 */
                if (CTX->isComment()) {
                    CTX->endBlockComment();
                } else {
                    CTX->raiseError("unexpected token '*/'");
                }
            }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 69 "seqc_lexer.l"
{
                /* Rule 3: Line comment start — action @0x2c8c1c */
                if (!CTX->isComment()) {
                    CTX->startLineComment();
                }
            }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 76 "seqc_lexer.l"
{ if (!CTX->isComment()) return KW_CONST;   }  /* Rule 4  — 0x2c8bac */
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 77 "seqc_lexer.l"
{ if (!CTX->isComment()) return KW_CVAR;    }  /* Rule 5  — 0x2c8dbf */
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 78 "seqc_lexer.l"
{ if (!CTX->isComment()) return KW_STRING;   }  /* Rule 6  — 0x2c8ddb */
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 79 "seqc_lexer.l"
{ if (!CTX->isComment()) return KW_VAR;      }  /* Rule 7  — 0x2c8bc8 */
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 80 "seqc_lexer.l"
{ if (!CTX->isComment()) return KW_VOID;     }  /* Rule 8  — 0x2c8be4 */
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 81 "seqc_lexer.l"
{ if (!CTX->isComment()) return KW_WAVE;     }  /* Rule 9  — 0x2c8d87 */
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 82 "seqc_lexer.l"
{ if (!CTX->isComment()) return KW_BREAK;    }  /* Rule 10 — 0x2c8e67 */
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 83 "seqc_lexer.l"
{ if (!CTX->isComment()) return KW_CASE;     }  /* Rule 11 — 0x2c8c72 */
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 84 "seqc_lexer.l"
{ if (!CTX->isComment()) return KW_CONTINUE; }  /* Rule 12 — 0x2c8df7 */
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 85 "seqc_lexer.l"
{ if (!CTX->isComment()) return KW_DEFAULT;  }  /* Rule 13 — 0x2c8acc */
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 86 "seqc_lexer.l"
{ if (!CTX->isComment()) return KW_DO;       }  /* Rule 14 — 0x2c8a94 */
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 87 "seqc_lexer.l"
{ if (!CTX->isComment()) return KW_ELSE;     }  /* Rule 15 — 0x2c8ab0 */
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 88 "seqc_lexer.l"
{ if (!CTX->isComment()) return KW_FOR;      }  /* Rule 16 — 0x2c8e13 */
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 89 "seqc_lexer.l"
{ if (!CTX->isComment()) return KW_IF;       }  /* Rule 17 — 0x2c8caa */
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 90 "seqc_lexer.l"
{ if (!CTX->isComment()) return KW_REPEAT;   }  /* Rule 18 — 0x2c8e9f */
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 91 "seqc_lexer.l"
{ if (!CTX->isComment()) return KW_RETURN;   }  /* Rule 19 — 0x2c8f0b */
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 92 "seqc_lexer.l"
{ if (!CTX->isComment()) return KW_SWITCH;   }  /* Rule 20 — 0x2c8b74 */
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 93 "seqc_lexer.l"
{ if (!CTX->isComment()) return KW_WHILE;    }  /* Rule 21 — 0x2c8e83 */
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 95 "seqc_lexer.l"
{
                /* Rule 22: Identifier — action @0x2c8da3 */
                if (CTX->isComment()) { /* skip */ }
                else {
                    yylval->sval = yytext;
                    return IDENTIFIER;
                }
            }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 104 "seqc_lexer.l"
{
                /* Rule 23: Hex integer — action @0x2c8f27 -> 0x2c9340 */
                if (CTX->isComment()) { /* skip */ }
                else {
                    unsigned int tmp;
                    sscanf(yytext + 2, "%x", &tmp);
                    yylval->dval = static_cast<double>(static_cast<int64_t>(tmp));
                    return CONSTANT;
                }
            }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 115 "seqc_lexer.l"
{
                /* Rule 24: Binary integer — action @0x2c8ebb -> stoull */
                if (CTX->isComment()) { /* skip */ }
                else {
                    std::string s(yytext);
                    unsigned long long val = std::stoull(s.substr(2), nullptr, 2);
                    yylval->dval = static_cast<double>(val);
                    return CONSTANT;
                }
            }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 126 "seqc_lexer.l"
{
                /* Rule 25: Leading-zero integer — action @0x2c8f5f -> 0x2c9290 */
                if (CTX->isComment()) { /* skip */ }
                else {
                    int tmp;
                    sscanf(yytext, "%d", &tmp);
                    yylval->dval = static_cast<double>(tmp);
                    return CONSTANT;
                }
            }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 137 "seqc_lexer.l"
{
                /* Rule 26: Decimal integer — action @0x2c8e4b -> 0x2c9290 */
                if (CTX->isComment()) { /* skip */ }
                else {
                    int tmp;
                    sscanf(yytext, "%d", &tmp);
                    yylval->dval = static_cast<double>(tmp);
                    return CONSTANT;
                }
            }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 148 "seqc_lexer.l"
{
                /* Rule 27: Integer with exponent — action @0x2c8f7b -> 0x2c9253 */
                if (CTX->isComment()) { /* skip */ }
                else {
                    sscanf(yytext, "%lf", &yylval->dval);
                    return CONSTANT;
                }
            }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 157 "seqc_lexer.l"
{
                /* Rule 28: Float (digits after dot) — action @0x2c8a5c -> 0x2c9253 */
                if (CTX->isComment()) { /* skip */ }
                else {
                    sscanf(yytext, "%lf", &yylval->dval);
                    return CONSTANT;
                }
            }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 166 "seqc_lexer.l"
{
                /* Rule 29: Float (dot suffix) — action @0x2c8b90 -> 0x2c9253 */
                if (CTX->isComment()) { /* skip */ }
                else {
                    sscanf(yytext, "%lf", &yylval->dval);
                    return CONSTANT;
                }
            }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 175 "seqc_lexer.l"
{
                /* Rule 30: Single-quoted string — action @0x2c87bc -> 0x2c9276 */
                if (CTX->isComment()) { /* skip */ }
                else {
                    yylval->sval = yytext;
                    return STRING_LITERAL;
                }
            }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 184 "seqc_lexer.l"
{
                /* Rule 31: Double-quoted string — action @0x2c87a0 -> 0x2c9276 */
                if (CTX->isComment()) { /* skip */ }
                else {
                    yylval->sval = yytext;
                    return STRING_LITERAL;
                }
            }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 193 "seqc_lexer.l"
{ if (!CTX->isComment()) return RSH_ASSIGN;  }  /* Rule 32 — 0x2c8c8e */
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 194 "seqc_lexer.l"
{ if (!CTX->isComment()) return LSH_ASSIGN;  }  /* Rule 33 — 0x2c8a40 */
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 195 "seqc_lexer.l"
{ if (!CTX->isComment()) return ADD_ASSIGN;   }  /* Rule 34 — 0x2c8ae8 */
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 196 "seqc_lexer.l"
{ if (!CTX->isComment()) return SUB_ASSIGN;   }  /* Rule 35 — 0x2c8880 */
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 197 "seqc_lexer.l"
{ if (!CTX->isComment()) return MUL_ASSIGN;   }  /* Rule 36 — 0x2c8feb */
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 198 "seqc_lexer.l"
{ if (!CTX->isComment()) return DIV_ASSIGN;   }  /* Rule 37 — 0x2c88b8 */
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 199 "seqc_lexer.l"
{ if (!CTX->isComment()) return MOD_ASSIGN;   }  /* Rule 38 — 0x2c8810 */
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 200 "seqc_lexer.l"
{ if (!CTX->isComment()) return AND_ASSIGN;   }  /* Rule 39 — 0x2c88d4 */
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 201 "seqc_lexer.l"
{ if (!CTX->isComment()) return XOR_ASSIGN;   }  /* Rule 40 — 0x2c8f97 */
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 202 "seqc_lexer.l"
{ if (!CTX->isComment()) return OR_ASSIGN;    }  /* Rule 41 — 0x2c8ce2 */
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 203 "seqc_lexer.l"
{ if (!CTX->isComment()) return RSH_OP;       }  /* Rule 42 — 0x2c8b3c */
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 204 "seqc_lexer.l"
{ if (!CTX->isComment()) return LSH_OP;       }  /* Rule 43 — 0x2c89ec */
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 205 "seqc_lexer.l"
{ if (!CTX->isComment()) return INC_OP;       }  /* Rule 44 — 0x2c8998 */
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 206 "seqc_lexer.l"
{ if (!CTX->isComment()) return DEC_OP;       }  /* Rule 45 — 0x2c8fb3 */
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 207 "seqc_lexer.l"
{ if (!CTX->isComment()) return AND_OP;       }  /* Rule 46 — 0x2c882c */
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 208 "seqc_lexer.l"
{ if (!CTX->isComment()) return OR_OP;        }  /* Rule 47 — 0x2c8944 */
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 209 "seqc_lexer.l"
{ if (!CTX->isComment()) return LE_OP;        }  /* Rule 48 — 0x2c8b58 */
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 210 "seqc_lexer.l"
{ if (!CTX->isComment()) return GE_OP;        }  /* Rule 49 — 0x2c8864 */
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 211 "seqc_lexer.l"
{ if (!CTX->isComment()) return EQ_OP;        }  /* Rule 50 — 0x2c8fcf */
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 212 "seqc_lexer.l"
{ if (!CTX->isComment()) return NE_OP;        }  /* Rule 51 — 0x2c8b20 */
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 214 "seqc_lexer.l"
{ if (!CTX->isComment()) return ';';  }  /* Rule 52 — 0x2c8a08 */
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 215 "seqc_lexer.l"
{ if (!CTX->isComment()) return '{';  }  /* Rule 53 — 0x2c8960 */
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 216 "seqc_lexer.l"
{ if (!CTX->isComment()) return '}';  }  /* Rule 54 — 0x2c89d0 */
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 217 "seqc_lexer.l"
{ if (!CTX->isComment()) return ',';  }  /* Rule 55 — 0x2c8e2f */
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 218 "seqc_lexer.l"
{ if (!CTX->isComment()) return ':';  }  /* Rule 56 — 0x2c8a78 */
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 219 "seqc_lexer.l"
{ if (!CTX->isComment()) return '=';  }  /* Rule 57 — 0x2c8cc6 */
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 220 "seqc_lexer.l"
{ if (!CTX->isComment()) return '(';  }  /* Rule 58 — 0x2c88f0 */
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 221 "seqc_lexer.l"
{ if (!CTX->isComment()) return ')';  }  /* Rule 59 — 0x2c8928 */
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 222 "seqc_lexer.l"
{ if (!CTX->isComment()) return '[';  }  /* Rule 60 — 0x2c9007 */
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 223 "seqc_lexer.l"
{ if (!CTX->isComment()) return ']';  }  /* Rule 61 — 0x2c889c */
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 224 "seqc_lexer.l"
{ if (!CTX->isComment()) return '.';  }  /* Rule 62 — 0x2c9023 */
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 225 "seqc_lexer.l"
{ if (!CTX->isComment()) return '&';  }  /* Rule 63 — 0x2c8a24 */
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 226 "seqc_lexer.l"
{ if (!CTX->isComment()) return '!';  }  /* Rule 64 — 0x2c903f */
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 227 "seqc_lexer.l"
{ if (!CTX->isComment()) return '~';  }  /* Rule 65 — 0x2c89b4 */
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 228 "seqc_lexer.l"
{ if (!CTX->isComment()) return '-';  }  /* Rule 66 — 0x2c87f4 */
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 229 "seqc_lexer.l"
{ if (!CTX->isComment()) return '+';  }  /* Rule 67 — 0x2c9077 */
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 230 "seqc_lexer.l"
{ if (!CTX->isComment()) return '*';  }  /* Rule 68 — 0x2c8c00 */
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 231 "seqc_lexer.l"
{ if (!CTX->isComment()) return '/';  }  /* Rule 69 — 0x2c8b04 */
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 232 "seqc_lexer.l"
{ if (!CTX->isComment()) return '%';  }  /* Rule 70 — 0x2c897c */
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 233 "seqc_lexer.l"
{ if (!CTX->isComment()) return '<';  }  /* Rule 71 — 0x2c87bc */
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 234 "seqc_lexer.l"
{ if (!CTX->isComment()) return '>';  }  /* Rule 72 — 0x2c905b */
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 235 "seqc_lexer.l"
{ if (!CTX->isComment()) return '^';  }  /* Rule 73 — 0x2c87d8 */
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 236 "seqc_lexer.l"
{ if (!CTX->isComment()) return '|';  }  /* Rule 74 — 0x2c890c */
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 237 "seqc_lexer.l"
{ if (!CTX->isComment()) return '?';  }  /* Rule 75 — 0x2c8848 */
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 239 "seqc_lexer.l"
{
                /* Rule 76: Whitespace — skip (includes \v and \f) */
            }
	YY_BREAK
case 77:
/* rule 77 can match eol */
YY_RULE_SETUP
#line 243 "seqc_lexer.l"
{
                /* Rule 77: Newline — action @0x2c8f43 */
                CTX->incrementLineNumber();
            }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 248 "seqc_lexer.l"
{
                /* Rule 78: Carriage return — action @0x2c8f4b */
                CTX->endLineComment();
            }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 253 "seqc_lexer.l"
{
                /* Rule 79: Unexpected character — action @0x2c8cfe */
                if (!CTX->isComment()) {
                    CTX->raiseError("Unexpected character");
                }
            }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 260 "seqc_lexer.l"
{
                /* Rule 81: End of input — action @0x2c7e9f / 0x2c9237 */
                return 0;
            }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 265 "seqc_lexer.l"
ECHO;
	YY_BREAK
#line 1706 "seqc_lexer.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 168 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 168 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 167);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * yyget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void yyset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 265 "seqc_lexer.l"


