// ============================================================================
// Forward declarations for flex/bison generated assembler lexer/parser.
// (asm_lexer.l / asm_parser.y, auto-regenerated by CMake)
// ============================================================================

#pragma once

struct yy_buffer_state;

namespace zhinst { class AsmParserContext; class AsmExpression; }

int asmlex_init_extra(zhinst::AsmParserContext* extra, void** scanner);
yy_buffer_state* asm_scan_string(const char* str, void* scanner);
void asm_delete_buffer(yy_buffer_state* buf, void* scanner);
int asmlex_destroy(void* scanner);
int asmparse(zhinst::AsmParserContext* ctx, zhinst::AsmExpression** result, void* scanner);
