// ============================================================================
// Reconstructed from disassembly of _seqc_compiler.so
// Waveform base class (0xD8 bytes) + nested File struct (0x40 bytes)
//
// Source path (from debug strings):
//   /builds/labone/labone/ziAWG/ziAWGUtils/src/main/include/Waveform
//
// Confirmed from:
//   - Full constructor (0x2a71e0)
//   - Copy constructor (0x2a8ff0)
//   - Destructor (0x1152e0)
//   - toJson (0x2a33c0)
//   - fromJson (0x2a54b0)
//   - operator== (0x2a9510)
//   - getSizePerDevice (0x1d5c30)
//   - Copy-rename ctor (0x114f10)
// ============================================================================
#pragma once

#include <cstdint>
#include <memory>
#include <string>
#include <unordered_map>
#include <vector>

#include "zhinst/waveform/signal.hpp"
#include "zhinst/asm/address_impl.hpp"

namespace zhinst {

struct DeviceConstants;  // forward declaration

// ============================================================================
// Waveform::File — source file reference (0x40 bytes)
//
// Offset  Size  Type              Name
// ------  ----  ----              ----
// 0x00    24    std::string       name
// 0x18     4    FormatType        formatType
// 0x1C     4    int32_t           columnMode
// 0x20     4    int32_t           isIntegerFormat
// 0x24     4    (padding)
// 0x28     8    uint*             fileHash begin  }
// 0x30     8    uint*             fileHash end    } vector<unsigned int> (hash)
// 0x38     8    uint*             fileHash cap    }
// 0x40          END
// ============================================================================
//! \brief Source-file metadata for a `Waveform`: the path to the
//! original sample file (CSV, RAW, or generated), the detected
//! text/format variant, and the cache hash of its contents.
//!
//! \details Embedded in `Waveform` via `shared_ptr` so multiple
//! waveforms that came from the same input file share the same
//! descriptor.
struct WaveformFile {
    //! \brief Source-file kind: text CSV, raw binary, or generated
    //! programmatically by a SeqC waveform-factory function.
    enum class Type : int {
        CSV = 0,    //!< Comma-separated text file.
        RAW = 1,    //!< Raw binary sample file.
        GEN = 2,    //!< Generated by a SeqC waveform-factory function (no source file).
    };

    // FormatType — detected data layout within a CSV file (+0x18 field)
    //   AutoDetect    = 0: not yet determined; detection runs on first data line
    //   AwgInteger    = 1: single-column AWG integer format (hex "0x..." values)
    //   MultiColFloat = 2: multi-column floating-point (>2 columns detected)
    //! \brief Detected data layout within a CSV source file. The
    //! parser leaves this at `AutoDetect` until the first data line
    //! is read, at which point it commits to `AwgInteger` (hex
    //! `0x...` values, single column) or `MultiColFloat`
    //! (floating-point, more than two columns).
    enum class FormatType : int32_t {
        AutoDetect    = 0,  //!< Not yet determined; detection runs on the first data line.
        AwgInteger    = 1,  //!< Single-column AWG integer format (hex `0x...` values).
        MultiColFloat = 2,  //!< Multi-column floating-point (more than two columns detected).
    };

    std::string name;                   //!< Source-file path. +0x00
    FormatType formatType;              //!< Detected text-file layout (relevant for CSV; left at `AutoDetect` for RAW/GEN). +0x18
    int32_t columnMode;                 //!< CSV column-mode tag carried alongside `formatType`. Default-constructed to `0`; both `WaveformIR` constructors force it to `1` whenever a `WaveformFile` is attached. Compared field-for-field by `WaveformFile::operator==`. No discriminator-style read of this field has been located in the binary, so the semantic distinction between values `0` and `1` is known only via the "WaveformIR forces to 1" invariant. +0x1C
    int32_t isIntegerFormat;            //!< Cached integer-format flag set by the parser when an integer layout is committed. +0x20
    std::vector<unsigned int> fileHash; //!< Hash of the source-file contents (from `CachedParser::getHash`), used to cache parsed data across compilations. +0x28

    // Static string converters (lazy-initialized static maps)
    //! \brief Convert a `Type` value to its lowercase three-letter
    //! string form (`"csv"`, `"raw"`, `"gen"`).
    //! \param type Type enumerator.
    //! \return Lowercase string for the type.
    //! \throws std::out_of_range when `type` is not a known enumerator.
    static std::string typeToStr(Type type);         // 0x2a3a90
    //! \brief Convert one of the three lowercase strings (`"csv"`,
    //! `"raw"`, `"gen"`) back into its `Type` enumerator.
    //! \param str Lowercase string.
    //! \return Corresponding enumerator.
    //! \throws std::out_of_range when `str` is not one of the three
    //! known values.
    static Type typeFromStr(std::string str);        // 0x2a63c0

    //! \brief Field-wise equality on `name`, `formatType`,
    //! `columnMode`, `isIntegerFormat`, and `fileHash`.
    //! \param other Other `WaveformFile` to compare against.
    //! \return `true` if every compared field matches.
    bool operator==(WaveformFile const& other) const;  // 0x2a9680

    //! \brief Construct a `WaveformFile` from a NUL-terminated path.
    //! \details `formatType` is initialised to `AutoDetect`,
    //! `columnMode` and `isIntegerFormat` to 0, and `fileHash` is
    //! left empty; the parser fills these later.
    //! \param filename Source-file path; copied into `name`.
    explicit WaveformFile(const char* filename);     // 0x2a7ff0
    //! \brief Convenience constructor delegating to the
    //! `const char*` form.
    //! \param filename Source-file path; copied into `name`.
    explicit WaveformFile(const std::string& filename) : WaveformFile(filename.c_str()) {}
};

// ============================================================================
// Waveform base class — 0xD8 bytes
//
// Offset  Size  Type                        Name              Notes
// ------  ----  ----                        ----              -----
// 0x00    24    std::string                 name
// 0x18     4    WaveformFile::Type          waveformType      0=CSV, 1=RAW, 2=GEN
// 0x1C     4    (padding)
// 0x20    24    std::string                 functionArgs     "functionArgs" in JSON
// 0x38    16    shared_ptr<WaveformFile>    file              source file
// 0x48     1    bool                        used              "load" in JSON
// 0x49     3    (padding)
// 0x4C     4    uint32_t                    addressValue      "globalAddress" in JSON
// 0x50    24    std::string                 funDescrName       "genFunc" in JSON
// 0x68     4    uint32_t                    playConfig          "playConfig" in JSON
// 0x6C     4    int32_t                     playIndex         "waveIndex" in JSON
// 0x70     4    int                         minLengthSamples       "minLengthSamples" in JSON
// 0x74     4    int                         field74           "allocationSize" in JSON
// 0x78     8    DeviceConstants*            deviceConstants
// 0x80    0x58  Signal                      signal
// 0xD8          END
// ============================================================================
//! \brief Front-end representation of one waveform: name, source-file
//! reference, the parsed `Signal` payload, the play-time
//! configuration packed into `playConfig`, the placement-time
//! address fields, and the device-constants pointer that produced
//! it.
//!
//! \details Each unique waveform parsed or generated from SeqC source
//! becomes one `Waveform` instance. The IR / back-end stage extends
//! this with `WaveformIR`, which adds the prefetch / placement
//! flags. JSON round-tripping (`toJson` / `fromJson`) supports the
//! metadata sections written into the output ELF.
struct Waveform {
    //! \brief Convenience alias for the per-waveform source-file descriptor type.
    using File = WaveformFile;

    std::string name;                                //!< User-visible waveform name (the SeqC variable name or generated identifier). JSON key `"name"`. +0x00
    File::Type waveformType;                         //!< Source-file kind (`CSV`, `RAW`, or `GEN`). JSON key `"type"` (encoded via `File::typeToStr`). +0x18
    std::string functionArgs;                        //!< Stringified argument list captured for generated waveforms (the SeqC factory call's argument tuple). JSON key `"functionArgs"`. +0x20
    std::shared_ptr<File> file;                      //!< Optional source-file descriptor; null for `GEN` waveforms. JSON key `"fileName"` (only the filename string is round-tripped). +0x38
    bool used;                                       //!< Whether the waveform is actually played by the program (set by usage analysis); `false` allows the back-end to drop it. JSON key `"load"`. +0x48
    uint32_t addressValue;                           //!< Global memory address assigned to this waveform during placement. JSON key `"globalAddress"`. +0x4C
    std::string funDescrName;                        //!< Generator-function descriptor (the `genFunc` name used to recreate `GEN` waveforms). JSON key `"genFunc"`. +0x50
    uint32_t playConfig;                             //!< Encoded `PlayConfig` word (output of `PlayConfig::encodeCwvf`) used at play time. JSON key `"playConfig"`. +0x68
    int32_t waveIndex;                               //!< Index assigned in the device wavetable; `-1` until placement. JSON key `"waveIndex"`. +0x6C
    int minLengthSamples;                            //!< Minimum-length-samples constraint propagated from the device's grain rules. JSON key `"minLengthSamples"`. +0x70
    int allocationByteSize;                          //!< Byte-size reserved in waveform memory for this entry on the target device (output of `getSizePerDevice` rounded for placement). JSON key `"allocationSize"`. +0x74
    const DeviceConstants* deviceConstants;          //!< Non-owning pointer to the device-constants record used to size and validate this waveform. +0x78
    Signal signal;                                   //!< Parsed sample buffer plus marker / marker-bits descriptors. JSON key `"signal"`. +0x80

    // --- Constructors / Destructor ---

    //! \brief Default-construct a zero-initialised `Waveform` (used by
    //! factory paths that fill fields incrementally).
    Waveform() = default;

    // Full 13-parameter constructor — 0x2a71e0
    //! \brief Construct a `Waveform` from a complete set of field
    //! values, matching the 13-parameter form used by the front-end
    //! waveform factory and by `fromJson`.
    //! \param name User-visible waveform name.
    //! \param type Source-file kind.
    //! \param functionArgs Stringified factory-call argument list.
    //! \param file Optional source-file descriptor (may be null).
    //! \param used Whether usage analysis flagged this waveform as played.
    //! \param addr Global memory address assigned to this waveform.
    //! \param genFunc Generator-function descriptor name.
    //! \param playConfig Encoded `PlayConfig` word for this waveform.
    //! \param playIndex Wavetable index (or `-1` until placement).
    //! \param minLengthSamples Minimum-length constraint in samples.
    //! \param allocationByteSize Byte-size to reserve for this entry.
    //! \param dc Device-constants record; the address is stored in
    //! `deviceConstants` (the caller must keep it alive).
    //! \param signal Parsed sample buffer; moved in.
    Waveform(std::string name, File::Type type, std::string functionArgs,
             std::shared_ptr<File> file, bool used,
             detail::AddressImpl<uint32_t> addr, std::string genFunc,
             int playConfig, int playIndex, int minLengthSamples, int allocationByteSize,
             DeviceConstants const& dc, Signal signal);

    // Copy-rename constructor — 0x114f10
    //! \brief Copy-construct a `Waveform` from `*source` while
    //! replacing its name.
    //! \details All other fields are deep-copied from `*source`,
    //! including the `Signal` payload. The new name is moved into
    //! place. `source` is taken by value so the caller can pass a
    //! shared pointer without committing to ownership transfer.
    //! \param source Shared pointer to the waveform to copy from.
    //! \param newName New name for the cloned waveform; moved in.
    Waveform(std::shared_ptr<Waveform> source, std::string newName);

    // Copy constructor — 0x2a8ff0
    //! \brief Deep-copy constructor.
    //! \param other Source waveform to copy.
    Waveform(Waveform const& other);

    // Destructor — 0x1152e0
    //! \brief Destructor; releases all owned strings, the
    //! `shared_ptr<File>`, and the embedded `Signal`'s buffers.
    ~Waveform();

    // --- Methods ---

    //! \brief Serialise this waveform to a JSON object with the
    //! twelve keys documented on each member field above.
    //! \return JSON value carrying the serialised representation.
    boost::json::value toJson() const;              // 0x2a33c0
    //! \brief Deserialise a `Waveform` from its JSON object form.
    //! \param json JSON value expected to be an object with the keys
    //! produced by `toJson`.
    //! \param dc Device-constants record retained by reference in the
    //! reconstructed waveform; the caller must keep it alive.
    //! \return The deserialised waveform.
    static Waveform fromJson(boost::json::value const& json,
                             DeviceConstants const& dc);  // 0x2a54b0
    //! \brief Compute the byte size this waveform occupies in the
    //! target device's waveform memory.
    //! \details Length is rounded up to the device's grain size,
    //! clamped to the device-specific minimum length, multiplied by
    //! the channel count and bits-per-sample, and finally rounded up
    //! to a whole number of bytes. Returns `0` for an empty signal.
    //! \return Per-device byte size.
    uint32_t getSizePerDevice() const;              // 0x1d5c30
    //! \brief Field-wise equality comparison, including the embedded
    //! `Signal` (compared with the tolerance documented on
    //! `Signal::operator==`).
    //! \param other Waveform to compare against.
    //! \return `true` if every compared field matches.
    bool operator==(Waveform const& other) const;   // 0x2a9510

    // Convenience accessor
    //! \brief Const access to the waveform's user-visible name.
    //! \return Reference to `name`.
    std::string const& getName() const { return name; }
};

} // namespace zhinst
