#!/usr/bin/env python3
"""Generate prefetch-pressure stress .seqc files.

Outputs are written into the parent dir (tests/cases/stress/). Re-running
this script overwrites them. Each file's header comment notes the generator
parameters so the source-of-truth is reproducible.

Targets:
- B1: 256 short waves played linearly (no gaps).
- B2: 384 short waves played linearly (cross 256 boundary).
- B3: 512 short waves played linearly (heavy; orig may emit prefetch error).
- B8: ~200 waves with mixed magic lengths.
- B9: 300 wave declarations of which only ~50 are unique (dedup eligible).
- C1: UHFQA 100 short waves linear.
- C2: UHFQA >1024 distinct waves to trip the wave-mem limit (IF-192/196).

HDAWG cases use playWave(1, 2, w) (dual-channel, 384-sample-aligned).
UHFQA cases use playWave(1, w) and 16-sample-aligned waves (UHFQA min).
"""
import os
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent  # tests/cases/stress/

def header(name, descr):
    return (f"// AUTO-GENERATED by _gen/gen_prefetch_pressure.py — DO NOT EDIT BY HAND.\n"
            f"// {descr}\n"
            f"// Regenerate: python3 tests/cases/stress/_gen/gen_prefetch_pressure.py\n\n")

# ---------- HDAWG helpers ----------
# HDAWG playMinSamples=128, waveformMinSamples=32, sampleLength=64.
# Use 32-sample gauss waves: gauss(32, 16, sigma) where sigma varies.
# But playWave on HDAWG needs >=128 samples; use 128-sample short waves.

def hdawg_short_wave_decl(idx):
    """Return a unique HDAWG-eligible short waveform declaration."""
    # Vary sigma to ensure distinct cwvf cache entries.
    # gauss(N, center, sigma); 128 samples = HDAWG playMinSamples.
    sigma = 8 + (idx % 56)              # 8..63 — 56 distinct sigmas
    center = 32 + (idx // 56) % 64      # walk center too
    amp_num = 1 + (idx // (56*64)) % 9
    amp_den = 10
    return f"wave w{idx} = ({amp_num}.0/{amp_den}.0) * gauss(128, {center}, {sigma});"

def hdawg_short_play(idx):
    return f"playWave(1, 2, w{idx});"

def gen_hdawg_burst(name, n_waves, descr, with_long_breaks=False, long_every=64):
    lines = [header(name, descr)]
    for i in range(n_waves):
        lines.append(hdawg_short_wave_decl(i))
    lines.append("")
    for i in range(n_waves):
        lines.append(hdawg_short_play(i))
        if with_long_breaks and (i+1) % long_every == 0 and i+1 < n_waves:
            lines.append("playZero(8192);")
    lines.append("waitWave();")
    (OUT / f"{name}.seqc").write_text("\n".join(lines) + "\n")
    print(f"  wrote {name}.seqc ({n_waves} waves)")

def gen_hdawg_burst_then_long(name, n_short, n_runs, long_len=8192):
    """B4: short burst, long wave (gives prefetch room), more bursts.
    n_runs of (short burst of n_short, then 1 long wave).
    """
    descr = (f"B4: {n_runs} bursts of {n_short} short (128-sample) waves, "
             f"each followed by a {long_len}-sample play to give the "
             f"prefetcher room to schedule fetches.")
    lines = [header(name, descr)]
    total = n_short * n_runs + n_runs
    idx = 0
    # Declarations
    for r in range(n_runs):
        for k in range(n_short):
            lines.append(hdawg_short_wave_decl(idx))
            idx += 1
        lines.append(f"wave wlong{r} = gauss({long_len}, {long_len//2}, 200);")
    lines.append("")
    # Plays
    idx = 0
    for r in range(n_runs):
        for k in range(n_short):
            lines.append(hdawg_short_play(idx))
            idx += 1
        lines.append(f"playWave(1, 2, wlong{r});")
    lines.append("waitWave();")
    (OUT / f"{name}.seqc").write_text("\n".join(lines) + "\n")
    print(f"  wrote {name}.seqc ({total} waves)")

def gen_hdawg_burst_then_zero(name, n_short, n_runs, zero_len=8192):
    descr = (f"B5: {n_runs} bursts of {n_short} short waves, each "
             f"followed by playZero({zero_len}) — tests prefetcher's "
             f"recognition of idle slots.")
    lines = [header(name, descr)]
    idx = 0
    for r in range(n_runs):
        for k in range(n_short):
            lines.append(hdawg_short_wave_decl(idx))
            idx += 1
    lines.append("")
    idx = 0
    for r in range(n_runs):
        for k in range(n_short):
            lines.append(hdawg_short_play(idx))
            idx += 1
        lines.append(f"playZero({zero_len});")
    lines.append("waitWave();")
    (OUT / f"{name}.seqc").write_text("\n".join(lines) + "\n")
    print(f"  wrote {name}.seqc ({n_short*n_runs} waves)")

def gen_hdawg_branch_burst(name, n_each):
    """B6: two bursts of n_each each, separated by if/else with overlapping
    (but not identical) wave subsets in the branches."""
    descr = (f"B6: two {n_each}-wave bursts separated by if/else; both "
             "branches must be prefetch-feasible.")
    lines = [header(name, descr)]
    total = n_each * 3  # 2 bursts + branch waves
    for i in range(total):
        lines.append(hdawg_short_wave_decl(i))
    lines.append("")
    # First burst
    for i in range(n_each):
        lines.append(hdawg_short_play(i))
    # Branch
    lines.append("var sel = getUserReg(0);")
    lines.append("if (sel > 0) {")
    for i in range(n_each, n_each + n_each//2):
        lines.append("  " + hdawg_short_play(i))
    lines.append("} else {")
    for i in range(n_each + n_each//2, 2*n_each):
        lines.append("  " + hdawg_short_play(i))
    lines.append("}")
    # Second burst
    for i in range(2*n_each, 3*n_each):
        lines.append(hdawg_short_play(i))
    lines.append("waitWave();")
    (OUT / f"{name}.seqc").write_text("\n".join(lines) + "\n")
    print(f"  wrote {name}.seqc ({total} waves)")

def gen_hdawg_burst_in_loop(name, n_each, n_iters):
    """B7: short-wave burst inside a for-loop. Tests loop-carried prefetch."""
    descr = f"B7: {n_each}-wave burst in for-loop ({n_iters} iters)."
    lines = [header(name, descr)]
    for i in range(n_each):
        lines.append(hdawg_short_wave_decl(i))
    lines.append("")
    lines.append(f"for (var k = 0; k < {n_iters}; k = k + 1) {{")
    for i in range(n_each):
        lines.append("  " + hdawg_short_play(i))
    lines.append("}")
    lines.append("waitWave();")
    (OUT / f"{name}.seqc").write_text("\n".join(lines) + "\n")
    print(f"  wrote {name}.seqc ({n_each} waves × {n_iters} iters)")

def gen_hdawg_mixed_lengths(name, n_waves):
    """B8: mix of magic lengths (128, 192, 256, 384, 512, 768, 1024)."""
    descr = f"B8: {n_waves} waves with mixed magic lengths."
    lines = [header(name, descr)]
    lengths = [128, 192, 256, 384, 512, 768, 1024]
    for i in range(n_waves):
        L = lengths[i % len(lengths)]
        sigma = 8 + (i % (L // 4))
        center = L // 2
        lines.append(f"wave w{i} = 0.5 * gauss({L}, {center}, {sigma});")
    lines.append("")
    for i in range(n_waves):
        lines.append(f"playWave(1, 2, w{i});")
    lines.append("waitWave();")
    (OUT / f"{name}.seqc").write_text("\n".join(lines) + "\n")
    print(f"  wrote {name}.seqc ({n_waves} waves, mixed lengths)")

def gen_hdawg_dedup(name, n_decls, n_unique):
    """B9: many wave declarations but only n_unique distinct shapes.
    Each wave_i is constructed so that duplicates produce identical samples
    (use same numeric params, different wave name). Recon's cwvf-dedup
    must handle this gracefully under prefetch pressure.
    """
    descr = (f"B9: {n_decls} wave declarations of which only ~{n_unique} "
             f"are unique. Dedup-eligible duplicates under prefetch pressure.")
    lines = [header(name, descr)]
    for i in range(n_decls):
        u = i % n_unique
        sigma = 16 + (u % 32)
        center = 64
        amp = 0.5
        lines.append(f"wave w{i} = {amp} * gauss(128, {center}, {sigma});")
    lines.append("")
    for i in range(n_decls):
        lines.append(f"playWave(1, 2, w{i});")
    lines.append("waitWave();")
    (OUT / f"{name}.seqc").write_text("\n".join(lines) + "\n")
    print(f"  wrote {name}.seqc ({n_decls} decls, {n_unique} unique)")

def gen_hdawg_2ch_independent(name, n_each):
    """B10: independent waves on ch1 vs ch2, played alternately."""
    descr = (f"B10: {n_each} ch1-only + {n_each} ch2-only waves, "
             "alternately played.")
    lines = [header(name, descr)]
    for i in range(n_each):
        lines.append(f"wave a{i} = gauss(128, 64, {16 + (i % 48)});")
    for i in range(n_each):
        lines.append(f"wave b{i} = drag(128, 64, {16 + (i % 48)}, 0.05);")
    lines.append("")
    for i in range(n_each):
        lines.append(f"playWave(1, a{i});")
        lines.append(f"playWave(2, b{i});")
    lines.append("waitWave();")
    (OUT / f"{name}.seqc").write_text("\n".join(lines) + "\n")
    print(f"  wrote {name}.seqc ({2*n_each} waves)")

def gen_hdawg_marker_short(name, n_waves):
    """B11: short waves each carrying a marker. Stresses prefetch + marker
    channel encoding."""
    descr = f"B11: {n_waves} short marker-bearing waves."
    lines = [header(name, descr)]
    for i in range(n_waves):
        sigma = 8 + (i % 56)
        # marker bits cycle through 1,2,4 (2 marker bits → values 0..3 valid)
        mb = (i % 3) + 1
        lines.append(f"wave w{i} = 0.5*gauss(128, 64, {sigma}) + marker(128, {mb});")
    lines.append("")
    for i in range(n_waves):
        lines.append(f"playWave(1, 2, w{i});")
    lines.append("waitWave();")
    (OUT / f"{name}.seqc").write_text("\n".join(lines) + "\n")
    print(f"  wrote {name}.seqc ({n_waves} marker waves)")

def gen_hdawg_aWI_burst(name, n_waves):
    """B12: assignWaveIndex placeholders + executeTableEntry burst."""
    descr = f"B12: {n_waves} placeholders via assignWaveIndex + execTableEntry."
    lines = [header(name, descr)]
    for i in range(n_waves):
        lines.append(f"wave p{i} = placeholder(128);")
    lines.append("")
    for i in range(n_waves):
        lines.append(f'assignWaveIndex(1, 2, p{i}, {i});')
    lines.append("")
    for i in range(n_waves):
        lines.append(f"executeTableEntry({i});")
    lines.append("waitWave();")
    (OUT / f"{name}.seqc").write_text("\n".join(lines) + "\n")
    print(f"  wrote {name}.seqc ({n_waves} placeholders + ETE)")

def gen_hdawg_nested_branch_burst(name, n_each):
    """B13: nested if/else, four 64-wave subsets, only one runtime path."""
    descr = (f"B13: nested if/else with 4 burst subsets ({n_each} waves each); "
             "compiler must consider all paths.")
    lines = [header(name, descr)]
    total = n_each * 4
    for i in range(total):
        lines.append(hdawg_short_wave_decl(i))
    lines.append("")
    lines.append("var a = getUserReg(0);")
    lines.append("var b = getUserReg(1);")
    lines.append("if (a > 0) {")
    for i in range(0, n_each):
        lines.append("  " + hdawg_short_play(i))
    lines.append("  if (b > 0) {")
    for i in range(n_each, 2*n_each):
        lines.append("    " + hdawg_short_play(i))
    lines.append("  } else {")
    for i in range(2*n_each, 3*n_each):
        lines.append("    " + hdawg_short_play(i))
    lines.append("  }")
    lines.append("} else {")
    for i in range(3*n_each, 4*n_each):
        lines.append("  " + hdawg_short_play(i))
    lines.append("}")
    lines.append("waitWave();")
    (OUT / f"{name}.seqc").write_text("\n".join(lines) + "\n")
    print(f"  wrote {name}.seqc ({total} waves)")

# ---------- UHFQA helpers ----------
# UHFQA: playMinSamples=0, waveformMinSamples=16, waveformAlignment=4096(!),
# waveformMemSize=1024 entries, samplerate 1.8e9.
# UHFQA playWave: playWave(1, w) or playWave(2, w) — single channel.

def uhfqa_short_wave_decl(idx, length=32):
    """UHFQA short wave; vary sigma so each is distinct."""
    sigma = 4 + (idx % 28)
    center = length // 2
    amp_num = 1 + (idx // 28) % 9
    return f"wave wq{idx} = ({amp_num}.0/10.0) * gauss({length}, {center}, {sigma});"

def uhfqa_play(idx, ch=1):
    return f"playWave({ch}, wq{idx});"

def gen_uhfqa_short_burst(name, n_waves):
    descr = f"C1: UHFQA {n_waves} short (32-sample) waves linear."
    lines = [header(name, descr)]
    for i in range(n_waves):
        lines.append(uhfqa_short_wave_decl(i, length=32))
    lines.append("")
    for i in range(n_waves):
        lines.append(uhfqa_play(i))
    lines.append("waitWave();")
    (OUT / f"{name}.seqc").write_text("\n".join(lines) + "\n")
    print(f"  wrote {name}.seqc ({n_waves} UHFQA waves)")

def gen_uhfqa_1024_overflow(name, n_waves):
    """C2: more than 1024 distinct waves — triggers IF-192 / IF-196 sibling."""
    descr = (f"C2: UHFQA {n_waves} distinct waves — exceeds waveformMemSize "
             "limit of 1024. Should error in both compilers; tests IF-196 "
             "twin-bug hypothesis at awg_compiler.cpp check 11 (msg 0xF1).")
    lines = [header(name, descr)]
    for i in range(n_waves):
        lines.append(uhfqa_short_wave_decl(i, length=32))
    lines.append("")
    for i in range(n_waves):
        lines.append(uhfqa_play(i))
    lines.append("waitWave();")
    (OUT / f"{name}.seqc").write_text("\n".join(lines) + "\n")
    print(f"  wrote {name}.seqc ({n_waves} UHFQA waves; expect overflow error)")

def gen_uhfqa_aWI_burst(name, n_waves):
    descr = f"C3: UHFQA {n_waves} placeholders + assignWaveIndex burst."
    lines = [header(name, descr)]
    for i in range(n_waves):
        lines.append(f"wave pq{i} = placeholder(32);")
    lines.append("")
    for i in range(n_waves):
        lines.append(f'assignWaveIndex(1, pq{i}, {i});')
    lines.append("")
    for i in range(n_waves):
        lines.append(f"executeTableEntry({i});")
    lines.append("waitWave();")
    (OUT / f"{name}.seqc").write_text("\n".join(lines) + "\n")
    print(f"  wrote {name}.seqc ({n_waves} UHFQA placeholders)")

def gen_uhfqa_branch_burst(name, n_each):
    descr = f"C4: UHFQA {n_each}-wave bursts in if/else branches."
    lines = [header(name, descr)]
    for i in range(n_each * 3):
        lines.append(uhfqa_short_wave_decl(i, length=32))
    lines.append("")
    for i in range(n_each):
        lines.append(uhfqa_play(i))
    lines.append("var sel = getUserReg(0);")
    lines.append("if (sel > 0) {")
    for i in range(n_each, 2*n_each):
        lines.append("  " + uhfqa_play(i))
    lines.append("} else {")
    for i in range(2*n_each, 3*n_each):
        lines.append("  " + uhfqa_play(i))
    lines.append("}")
    lines.append("waitWave();")
    (OUT / f"{name}.seqc").write_text("\n".join(lines) + "\n")
    print(f"  wrote {name}.seqc ({3*n_each} UHFQA waves)")

def gen_uhfqa_2ch(name, n_each):
    descr = f"C5: UHFQA dual-channel pressure, {n_each} waves per channel."
    lines = [header(name, descr)]
    for i in range(n_each):
        lines.append(f"wave qa{i} = 0.5 * gauss(32, 16, {4 + (i%28)});")
        lines.append(f"wave qb{i} = 0.5 * drag(32, 16, {4 + (i%28)}, 0.05);")
    lines.append("")
    for i in range(n_each):
        lines.append(f"playWave(1, qa{i});")
        lines.append(f"playWave(2, qb{i});")
    lines.append("waitWave();")
    (OUT / f"{name}.seqc").write_text("\n".join(lines) + "\n")
    print(f"  wrote {name}.seqc ({2*n_each} UHFQA waves)")


def main():
    print("Generating B-track (HDAWG prefetch pressure):")
    gen_hdawg_burst("prefetch_256_short_linear", 256,
                    "B1: 256 short (128-sample) HDAWG waves played linearly.")
    gen_hdawg_burst("prefetch_384_short_linear", 384,
                    "B2: 384 short HDAWG waves linear (cross 256 boundary).")
    gen_hdawg_burst("prefetch_512_short_linear", 512,
                    "B3: 512 short HDAWG waves linear (heavy; orig may emit "
                    "prefetch error).")
    gen_hdawg_burst_then_long("prefetch_burst_then_long", 128, 3, long_len=8192)
    gen_hdawg_burst_then_zero("prefetch_burst_then_zero", 128, 3, zero_len=8192)
    gen_hdawg_branch_burst("prefetch_burst_branch", 64)
    gen_hdawg_burst_in_loop("prefetch_burst_in_loop", 64, 4)
    gen_hdawg_mixed_lengths("prefetch_mixed_short_lengths", 200)
    gen_hdawg_dedup("prefetch_dup_shapes", 300, 50)
    gen_hdawg_2ch_independent("prefetch_2ch_independent", 128)
    gen_hdawg_marker_short("prefetch_marker_short", 200)
    gen_hdawg_aWI_burst("prefetch_aWI_burst", 200)
    gen_hdawg_nested_branch_burst("prefetch_nested_branch_burst", 64)

    print("\nGenerating C-track (UHFQA prefetch pressure):")
    gen_uhfqa_short_burst("prefetch_uhfqa_short_burst", 100)
    gen_uhfqa_1024_overflow("prefetch_uhfqa_1024_entries", 1100)
    gen_uhfqa_aWI_burst("prefetch_uhfqa_aWI_burst", 200)
    gen_uhfqa_branch_burst("prefetch_uhfqa_branch_burst", 32)
    gen_uhfqa_2ch("prefetch_uhfqa_2ch", 64)

if __name__ == "__main__":
    main()
